# -*- coding: utf-8 -*-
"""clasterisaton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W9coZ2JBm6VFxCvmwleRDWS-nv-9HUUm
"""

import pandas as pd 
from copy import deepcopy
import numpy as np

df = pd.read_json('/content/dump.json')
dist_ = []
col = []
for i in range(len(df['_id'])):
  df[f'neighbour_{i}'] = df.iloc[i]['_id']
  df[f'dist_{i}'] = ((df.latitude - df.iloc[i]['latitude'])**2 \
                    + (df.longitude - df.iloc[i]['longitude'])**2) ** (1/2)
  df[f'area_{i}'] = df.iloc[i]['area'] + df['area']
  dist_.append(f'dist_{i}')
for i in range(len(df['_id'])):
  neighbours = pd.DataFrame(df.iloc[i][dist_]).astype(float)\
  .reset_index().nsmallest(5, columns=int(f'{i}'))
  neighbours = neighbours[neighbours[i] < 0.3]
  col.append(set(df.iloc[neighbours.index][['latitude',	'longitude']]\
  .apply(lambda x: (x['latitude'], x['longitude']), axis=1).values))
for i in range(len(col)):
  for j in range(i+1, len(col)):
    col[i] -= col[j]
res =[]
for i in col:
  if i:
    res.append(list(i))
print('''{
    "type": "FeatureCollection",
    "features":[''')
for i in range(len(res)):
  print('{"type": "Feature",')
  print(f'"id": {i},')
  print('''"geometry": {
        "type": "Polygon",
        "coordinates": [[''')
  for j in range(len(res[i])):
    if j+1 != len(res[i]):
      print(f'[{res[i][j][0]}, {res[i][j][1]}],')
    else:
      print(f'[{res[i][j][0]}, {res[i][j][1]}]')
  print(']]},')
  print('"properties": {')
  print('"dangerLevel": 2,')
  print(f'"id": {i}')
  if len(res) == i+1:
    print('}}]}')
  else:
    print('}},')
